# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      name: "Black Formatting"
      args: [--line-length=100]
      language_version: python3.11


- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: detect-private-key
    - id: name-tests-test
    # - id: no-commit-to-branch

- repo: local
  hooks:
    - id: pipreqs
      name: Generate requirements.txt
      entry: pipreqs --force .
      language: python
      additional_dependencies: [pipreqs]
      pass_filenames: false
      always_run: true

# # Don't need both black and ruff, but ruff looks promising. Supposed to be the fastest linter. Still going to keep it here.
# - repo: https://github.com/astral-sh/ruff-pre-commit
#   # Ruff version.
#   rev: v0.11.3
#   hooks:
#     # Run the linter.
#     - id: ruff
#     # Run the formatter.
#     - id: ruff-format
